(uiop:define-package :wlr
  (:use-reexport
   #:wlr/backend
   #:wlr/backend/session
   #:wlr/backend/wayland
   #:wlr/config
   #:wlr/error
   #:wlr/render/renderer
   #:wlr/types/box
   #:wlr/types/cursor
   #:wlr/types/data-device
   #:wlr/types/input-devices
   #:wlr/types/output
   #:wlr/types/output-damage
   #:wlr/types/output-layout
   #:wlr/types/seat
   #:wlr/types/xcursor-manager
   #:wlr/util/log
   #:wlr/xcursor
   #:wlr/wlr-version))
