(in-package #:wlr/types/surface)
(pkg-config-cflags "wlroots")
(cc-flags "-DWLR_USE_UNSTABLE")
(include "wlr/types/wlr_surface.h")

(cenum surface-state-field
       ((:buffer "WLR_SURFACE_STATE_BUFFER"))
       ((:surface-damage "WLR_SURFACE_STATE_SURFACE_DAMAGE"))
       ((:buffer-damage "WLR_SURFACE_STATE_BUFFER_DAMAGE"))
       ((:opaque-region "WLR_SURFACE_STATE_OPAQUE_REGION"))
       ((:input-region "WLR_SURFACE_STATE_INPUT_REGION"))
       ((:transform "WLR_SURFACE_STATE_TRANSFORM"))
       ((:scale "WLR_SURFACE_STATE_SCALE"))
       ((:frame-callback-list "WLR_SURFACE_STATE_FRAME_CALLBACK_LIST")))


(cstruct surface-state "struct wlr_surface_state"
	 ;; (committed :int32)
	 ;; (buffer-resource :pointer)
	 ;; (dx :int32)
	 ;; (dy :int32)
	 ;; (surface-damage :pointer)
	 ;; (buffer-damage :pointer)
	 ;; (opaque :pointer)
	 ;; (input :pointer)
	 (:transform "transform" :type wl-output-transform)
	 ;; (scale :int32)
	 ;; (frame-callback-list wl_list)
	 (:width "width" :type :int)
	 (:height "height" :type :int)
	 ;; (buffer-width :int)
	 ;; (buffer-height :int)
	 ;; (buffer-destroy (:struct wl_listener))
	 )

(cstruct surface-role "struct wlr_surface_role"
	 ;; (name :string)
	 ;; (commit :pointer)
	 ;; (precommit :pointer)
	 )

;; commented stuff may be incorrect:
(cstruct surface "struct wlr_surface"
	 ;; (resource :pointer)
	 ;; (renderer :pointer)
	 ;; (buffer :pointer)
	 ;; (sx :int)
	 ;; (sy :int)
	 (:current "current" :type (:struct surface-state))
	 ;; (buffer-damage :pointer)
	 ;; (opaque-region :pointer)
	 ;; (input-region :pointer)
	 ;; (current surface-state)
	 ;; (pending surface-state)
	 ;; (previous surface-state)
	 ;; (role :pointer)
	 ;; (role-data :pointer)
	 ;; (events :pointer)
	 ;; (subsurfaces :pointer)
	 ;; (subsurface-pending-list :pointer)
	 ;; (renderer-destroy :pointer)
	 ;; (data :pointer)
	 )

(cstruct subsurface-state "struct wlr_subsurface_state"
	 (x "x" :type :int32)
	 (y "y" :type :int32))

;; commented stuff may be incorrect:
(cstruct subsurface "struct wlr_subsurface"
	 ;; (resource :pointer)
	 ;; (surface :pointer)
	 ;; (parent :pointer)
	 ;; (current subsurface-state)
	 ;; (pending subsurface-state)
	 ;; (cached surface-state)
	 ;; (has-cache :pointer)
	 ;; (synchronized :pointer)
	 ;; (reordered :pointer)
	 ;; (parent-link :pointer)
	 ;; (parent-pending-link :pointer)
	 ;; (surface-destroy :pointer)
	 ;; (parent-destroy :pointer)
	 ;; (events :pointer)
	 ;; (data :pointer)
	 )
